<div class="alert alert-block alert-info">
<h>
<b>
<font size="6">
Example of using efp_gamess Plugin
</font>
</b>
</h>
</div>

In [1]:
import psi4
import numpy as np
import sys

In [2]:
sys.path.insert(0,'./../')
import efp_gamess

In [3]:
psi4.set_memory('1500 MB')

1500000000

<div class = "alert alert-block alert-warning">
<b>
Most of my development was using formaldehyde because it has a good electronic excitation solvent shift. So you can do EOM-CCSD after getting the SCF wfn computed in EFP presence
</b>
</div>

<div class = "alert alert-block alert-danger">
<b>
Use symmetry c1
</b>
</div>

In [4]:
formaldehyde = psi4.geometry("""
  C      -0.760348   -0.184626   -0.375944
  C      -0.359139    1.221670   -0.221730
  O      0.105433    0.221711    0.712263
  H      -1.062208    1.936726    0.204119
  H       0.417567    1.639988   -0.860411
  H      -0.232306   -0.767959   -1.131840
  C      -2.126083   -0.688966    0.012252
  H      -2.575921   -0.049412    0.778944
  H      -2.787098   -0.705369   -0.863386
  H      -2.062442   -1.709639    0.407385
  
symmetry c1
""")

In [27]:
psi4.set_options({'basis': 'aug-cc-pvdz','scf_type':'pk',
                  'puream':'true','mp2_type':'conv',
                 'e_convergence':'11','freeze_core':'true'})

<div class="alert alert-block alert-info">
<h>
<b>
<font size="6">
Call the plugin and get back scf energy and the scf wfn (computed in EFP presence)
</font>
</b>
</h>
</div>

In [6]:
egy,wfn=psi4.energy('efp_gamess',return_wfn=True)

Attention! This SCF may be density-fitted.

Printing ref_wfn.Fa().to_array()
[[ -1.12965722e+01   2.43973794e+00  -2.13291866e+00 ...,   2.22233806e-01
   -3.69338112e-01  -4.32809915e-01]
 [  2.43973794e+00  -1.13144345e+00  -3.95455363e-01 ...,   9.89439606e-02
   -1.51478929e-01  -1.93590829e-01]
 [ -2.13291866e+00  -3.95455363e-01  -1.39974720e+00 ...,   2.24070433e-01
   -2.51242533e-01  -4.89209255e-01]
 ..., 
 [  2.22233806e-01   9.89439606e-02   2.24070433e-01 ...,   5.24486521e-02
    8.33849775e-03   1.97010566e-01]
 [ -3.69338112e-01  -1.51478929e-01  -2.51242533e-01 ...,   8.33849775e-03
    9.39774995e-02  -4.81404789e-03]
 [ -4.32809915e-01  -1.93590829e-01  -4.89209255e-01 ...,   1.97010566e-01
   -4.81404789e-03  -3.63436928e-01]]

Printing C transformation matrix (as array)
[[ 1.  0.  0. ...,  0.  0.  0.]
 [ 0.  1.  0. ...,  0.  0.  0.]
 [ 0.  0.  1. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  1.]
 [ 0.  0.  0. ...,  1.  0.  0.]
 [ 0.  0.  0. ...,  0.  1.  0.]

<div class = "alert alert-info alert-block">
Save the Fock matrix as numpy array computed by plugin
</div>

In [7]:
Fa_efp=np.array(wfn.Fa())
Fa_efp

array([[ -1.13504662e+01,   2.45149025e+00,  -2.14298778e+00, ...,
          2.23246055e-01,  -3.71050703e-01,  -4.34851171e-01],
       [  2.45149025e+00,  -1.17710257e+00,  -4.22294257e-01, ...,
          1.01503763e-01,  -1.54768634e-01,  -2.00657713e-01],
       [ -2.14298778e+00,  -4.22294257e-01,  -1.43418490e+00, ...,
          2.27723431e-01,  -2.58582215e-01,  -5.01111931e-01],
       ..., 
       [  2.23246055e-01,   1.01503763e-01,   2.27723431e-01, ...,
          2.98747738e-02,   7.36761852e-03,   1.96776731e-01],
       [ -3.71050703e-01,  -1.54768634e-01,  -2.58582215e-01, ...,
          7.36761852e-03,   7.30967898e-02,  -6.94328197e-03],
       [ -4.34851171e-01,  -2.00657713e-01,  -5.01111931e-01, ...,
          1.96776731e-01,  -6.94328197e-03,  -3.87869845e-01]])

<div class = "alert alert-info alert-block">
Do the regular ol vacuum scf calculation and save the same info
</div>

In [8]:
egy_regular,wfn_regular=psi4.energy('scf',return_wfn=True)

In [9]:
Fa_vacuum=np.array(wfn_regular.Fa())
Fa_vacuum

array([[ -1.12965915e+01,   2.43974332e+00,  -2.13292155e+00, ...,
          2.22234119e-01,  -3.69338591e-01,  -4.32810478e-01],
       [  2.43974332e+00,  -1.13145523e+00,  -3.95461413e-01, ...,
          9.89450677e-02,  -1.51480136e-01,  -1.93592429e-01],
       [ -2.13292155e+00,  -3.95461413e-01,  -1.39975348e+00, ...,
          2.24071671e-01,  -2.51244123e-01,  -4.89211180e-01],
       ..., 
       [  2.22234119e-01,   9.89450677e-02,   2.24071671e-01, ...,
          5.24474301e-02,   8.33881174e-03,   1.97011296e-01],
       [ -3.69338591e-01,  -1.51480136e-01,  -2.51244123e-01, ...,
          8.33881174e-03,   9.39761384e-02,  -4.81475701e-03],
       [ -4.32810478e-01,  -1.93592429e-01,  -4.89211180e-01, ...,
          1.97011296e-01,  -4.81475701e-03,  -3.63438928e-01]])

<div class = "alert alert-info alert-block">
<h>
Look at the difference in the Fock matrix and the energy. See the effect of the water fragment potential
</h>
</div>

In [24]:
Fa_efp-Fa_vacuum

array([[-0.05387466,  0.01174693, -0.01006623, ...,  0.00101194,
        -0.00171211, -0.00204069],
       [ 0.01174693, -0.04564734, -0.02683284, ...,  0.0025587 ,
        -0.0032885 , -0.00706528],
       [-0.01006623, -0.02683284, -0.03443143, ...,  0.00365176,
        -0.00733809, -0.01190075],
       ..., 
       [ 0.00101194,  0.0025587 ,  0.00365176, ..., -0.02257266,
        -0.00097119, -0.00023456],
       [-0.00171211, -0.0032885 , -0.00733809, ..., -0.00097119,
        -0.02087935, -0.00212852],
       [-0.00204069, -0.00706528, -0.01190075, ..., -0.00023456,
        -0.00212852, -0.02443092]])

In [11]:
# Ref. energy unchanged because I just changed the Fock matrix.
# Would need to be recomputed
egy-egy_regular

-2.2834569790575188e-09

In [28]:
mp2Energy_inSolvent = psi4.energy('mp2',ref_wfn=wfn)

In [29]:
mp2Energy_inSolvent

-192.607056871285

In [30]:
mp2Energy_inVacuum=psi4.energy('mp2',ref_wfn=wfn_regular)

In [15]:
mp2Energy_inVacuum

-192.5813426982338

In [16]:
Hcore=np.array(wfn.H())
Hcore_vac=np.array(wfn_regular.H())

array([[-49.41284472,  11.16585838,  -9.05203301, ...,   0.93934796,
         -1.56410824,  -1.83437921],
       [ 11.16585838, -16.26293645,  -9.52541169, ...,   1.36339164,
         -2.28038237,  -2.78635291],
       [ -9.05203301,  -9.52541169, -15.03376446, ...,   2.32086594,
         -3.59594988,  -5.0298048 ],
       ..., 
       [  0.93934796,   1.36339164,   2.32086594, ...,  -6.63035341,
          0.08326745,   0.79411675],
       [ -1.56410824,  -2.28038237,  -3.59594988, ...,   0.08326745,
         -6.69051052,  -0.29298023],
       [ -1.83437921,  -2.78635291,  -5.0298048 , ...,   0.79411675,
         -0.29298023,  -8.44021587]])

In [17]:
nucRep=124.06044803594702

In [18]:
# I Didn't set the density matrix based on new coefficients so
# Can't use that expression
#np.tensordot(np.array(wfn.Da()),Hcore+Fa_efp,axes=2)+nucRep
#solv_E=np.einsum('pq,pq->',Fa_efp+Hcore,np.array(wfn.Da()))+nucRep

In [19]:
 vac_E=np.einsum('pq,pq->', Fa_vacuum + Hcore_vac, np.array(wfn_regular.Da())) + nucRep

In [25]:
vac_E

-191.93405301679255

In [22]:
# Recalculate SCF energy using coefficients from gamess
ndocc=16
Cocc = np.array(wfn.Ca())[:, :ndocc]                                                              
Dhere = np.einsum('pi,qi->pq', Cocc, Cocc)

In [32]:
scf_efp=np.einsum('pq,pq->',Fa_efp+Hcore,Dhere)+nucRep

In [33]:
scf_efp

-192.03526981534489